name: Sync DDL S2S API
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/rdme@6.5.0
        with:
          rdme: openapi ./docs/apis/audience/audience_external_api.yaml --key=${{ secrets.README_API_KEY }} --id=5f7d78862614180733ad85d7
